version: "3.9"
services:
  seaside-client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client-dc
    ports: 
      - 5173:5173
    volumes:
      - './client:/usr/app'  
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  seaside-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-dc
    ports:
      - 3000:3000
    volumes:
      - './server:/usr/app'  
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    