services:
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile # Points to the Dockerfile inside the frontend folder
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile # Points to the Dockerfile inside the backend folder
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
