name: Deploy to Auto Scaling Group

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      LAUNCH_TEMPLATE_NAME: "webapp-launch-template"
      INSTANCE_TYPE: "t3.micro"
      IMAGE_ID: "ami-0d9fcbc04c8714eaa"
      SECURITY_GROUP_ID: "sg-0b17225f5dc1be2b9"
      
      GITHUB_REPO_URL: "https://github.com/Xujia118/etude_docker"
      PROJECT_DIR: "/home/ubuntu/etude_docker" 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Create New Launch Template Version
      id: create-launch-template
      env:
        LAUNCH_TEMPLATE_NAME: ${{ env.LAUNCH_TEMPLATE_NAME }}
        INSTANCE_TYPE: ${{ env.INSTANCE_TYPE }}
        IMAGE_ID: ${{ env.IMAGE_ID }}
        SECURITY_GROUP_ID: ${{ env.SECURITY_GROUP_ID }}
        GITHUB_REPO_URL: ${{ env.GITHUB_REPO_URL }}
        PROJECT_DR: ${{ env.PROJECT_DIR }}
      run: |
        # Encode the User Data script
        USER_DATA=$(cat << EOF
        #!/bin/bash
        sudo apt upgrade -y

        if [ ! -d "$PROJECT_DIR" ]; then
          git clone $GITHUB_REPO_URL $PROJECT_DIR
        else
          cd $PROJECT_DIR
          git config --system --add safe.directory $PROJECT_DIR
          git pull origin main
        fi

        cd $PROJECT_DIR
        sudo docker-compose down
        sudo docker-compose build
        sudo docker-compose up -d
        EOF
        )

        ENCODED_USER_DATA=$(echo "$USER_DATA" | base64 -w 0)

        # Create a new launch template version
        NEW_VERSION=$(aws ec2 create-launch-template-version \
          --launch-template-name $LAUNCH_TEMPLATE_NAME \
          --version-description "New deployment $(date)" \
          --launch-template-data "{
            \"InstanceType\": \"$INSTANCE_TYPE\",
            \"ImageId\": \"$IMAGE_ID\",
            \"SecurityGroupIds\": [\"$SECURITY_GROUP_ID\"],
            \"UserData\": \"$ENCODED_USER_DATA\"
          }" | jq -r '.LaunchTemplateVersion.VersionNumber')
        echo "NEW_LAUNCH_TEMPLATE_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

    - name: Update Auto Scaling Group
      env: 
        ASG_NAME: "webapp-asg"  
        LAUNCH_TEMPLATE_NAME: ${{ env.LAUNCH_TEMPLATE_NAME }}
      run: |
        aws autoscaling update-auto-scaling-group \
          --auto-scaling-group-name $ASG_NAME \
          --launch-template "LaunchTemplateName=$LAUNCH_TEMPLATE_NAME,Version=$NEW_LAUNCH_TEMPLATE_VERSION"

    - name: Start Instance Refresh
      env: 
        ASG_NAME: "webapp-asg"  
      run: |
        aws autoscaling start-instance-refresh \
          --auto-scaling-group-name $ASG_NAME \
          --preferences '{"MinHealthyPercentage": 90, "InstanceWarmup": 300}'